# Generated by Django 5.2.12 on 2026-03-13 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('bonus_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Процент начисления бонусов (%)')),
                ('expiration_months', models.PositiveIntegerField(default=12, verbose_name='Срок действия бонусов (месяцев)')),
                ('min_bonus_to_spend', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Минимум бонусов для списания')),
            ],
            options={
                'verbose_name': 'Настройки бонусов',
                'verbose_name_plural': 'Настройки бонусов',
                'db_table': 'bonus_settings',
            },
        ),
        migrations.CreateModel(
            name='BonusLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('type', models.CharField(choices=[('earned', 'Начислено'), ('spent', 'Списано'), ('expired', 'Сгорело'), ('adjusted', 'Корректировка'), ('bonus', 'Бонус')], max_length=20, verbose_name='Тип операции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_entries', to='transactions.transaction', verbose_name='Транзакция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_ledger', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись бонусов',
                'verbose_name_plural': 'Журнал бонусов',
                'db_table': 'bonus_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('card_number', models.CharField(max_length=50, unique=True, verbose_name='Номер карты')),
                ('barcode_type', models.CharField(choices=[('code128', 'Code 128'), ('qr', 'QR Code'), ('ean13', 'EAN-13')], default='code128', max_length=20, verbose_name='Тип штрихкода')),
                ('is_virtual', models.BooleanField(default=True, verbose_name='Виртуальная карта')),
                ('has_physical_card', models.BooleanField(default=False, verbose_name='Привязана физическая карта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_cards', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Карта лояльности',
                'verbose_name_plural': 'Карты лояльности',
                'db_table': 'loyalty_cards',
            },
        ),
    ]
