# Generated by Django 5.2.12 on 2026-03-13 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('transaction_number', models.CharField(max_length=50, unique=True, verbose_name='Номер транзакции')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма чека')),
                ('bonus_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Начислено бонусов')),
                ('bonus_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Списано бонусов')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Завершена'), ('refunded', 'Возврат'), ('cancelled', 'Отменена')], default='completed', max_length=20, verbose_name='Статус')),
                ('receipt_url', models.URLField(blank=True, null=True, verbose_name='URL чека')),
                ('transaction_date', models.DateTimeField(verbose_name='Дата транзакции')),
                ('erp_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID в ERP')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='stores.store', verbose_name='Аптека')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, verbose_name='ID товара')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма по строке')),
                ('is_promotional', models.BooleanField(default=False, verbose_name='По акции')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_items', to='promotions.promotion', verbose_name='Акция')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.transaction', verbose_name='Транзакция')),
            ],
            options={
                'verbose_name': 'Позиция чека',
                'verbose_name_plural': 'Позиции чеков',
                'db_table': 'transaction_items',
            },
        ),
    ]
