# Generated by Django 5.2.12 on 2026-03-13 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('code', models.CharField(max_length=6, verbose_name='Код')),
                ('purpose', models.CharField(choices=[('login', 'Вход'), ('password_reset', 'Сброс пароля')], default='login', max_length=20, verbose_name='Назначение')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попыток')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
            ],
            options={
                'verbose_name': 'OTP код',
                'verbose_name_plural': 'OTP коды',
                'db_table': 'otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Токен')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токен сброса пароля',
                'verbose_name_plural': 'Токены сброса пароля',
                'db_table': 'password_reset_tokens',
            },
        ),
    ]
